<a href="https://colab.research.google.com/github/Sachinsen1295/Pandas/blob/Pandas/Wine_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random

In [ ]:
from  google.colab import drive

In [ ]:
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
wine_df= pd.read_csv("/content/drive/MyDrive/Data/winemag-data-130k-v2.csv")
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## Grouping and Sorting

In [ ]:
groupbypoints= wine_df.groupby("points").points.count()
groupbypoints

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [ ]:
wine_df.groupby("price").price.count()

price
4.0        11
5.0        46
6.0       120
7.0       433
8.0       892
         ...
1900.0      1
2000.0      2
2013.0      1
2500.0      2
3300.0      1
Name: price, Length: 390, dtype: int64

In [ ]:
wine_df.groupby("points").price.max(10)

points
80       69.0
81      130.0
82      150.0
83      225.0
84      225.0
85      320.0
86      170.0
87      800.0
88     3300.0
89      500.0
90      510.0
91     2013.0
92      750.0
93      770.0
94     1125.0
95      973.0
96     2500.0
97     2000.0
98     1900.0
99      850.0
100    1500.0
Name: price, dtype: float64

In [ ]:
wine_df.groupby("winery").apply(lambda x:x.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [ ]:
q=wine_df.groupby(["country","province"]).apply(lambda x:x.loc[x.points.idxmax()])
q.head(1)

#we need group data first by - country then province
# and afterthat start by max values in that column
#loc to lock the column "points"
#in lambda x is wine_df
#idxmax means -  returns a Series with the index of the maximum value for each
# column. By specifying the column axis ( axis='columns' ), the idxmax() method
 # returns a Series with the index of the maximum value for each row.

,,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,province,,,,,,,,,,,,,,
Argentina,Mendoza Province,82754,Argentina,"If the color doesn't tell the full story, the ...",Nicasia Vineyard,97,120.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Bodega Catena Zapata 2006 Nicasia Vineyard Mal...,Malbec,Bodega Catena Zapata

In [ ]:
wine_df.groupby("country").apply(lambda x:x.loc[x.points.idxmax()])

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,,
Argentina,82754,Argentina,"If the color doesn't tell the full story, the ...",Nicasia Vineyard,97,120.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Bodega Catena Zapata 2006 Nicasia Vineyard Mal...,Malbec,Bodega Catena Zapata
Armenia,66146,Armenia,"Deep salmon in color, this wine offers a bouqu...",Estate Bottled,88,15.0,Armenia,NaN,NaN,Mike DeSimone,@worldwineguys,Van Ardi 2015 Estate Bottled Rosé (Armenia),Rosé,Van Ardi
Australia,345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
Austria,109406,Austria,Opulent honey and lemon aromas waft from the g...,Zwischen den Seen Nummer 9 Trockenbeerenauslese,98,NaN,Burgenland,NaN,NaN,Roger Voss,@vossroger,Kracher 2008 Zwischen den Seen Nummer 9 Trocke...,Welschriesling,Kracher
Bosnia and Herzegovina,96759,Bosnia and Herzegovina,A mix of red and black fruits pervade on the n...,NaN,88,12.0,Mostar,NaN,NaN,Jeff Jenssen,@worldwineguys,Winery Čitluk 2011 Blatina (Mostar),Blatina,Winery Čitluk
Brazil,72991,Brazil,Stony polished white-fruit aromas are lean and...,Brut Nature,89,36.0,Pinto Bandeira,NaN,NaN,Michael Schachner,@wineschach,Cave Geisse 2013 Brut Nature Sparkling (Pinto ...,Sparkling Blend,Cave Geisse
Bulgaria,35926,Bulgaria,This Bulgarian red blend is produced under the...,CR,91,30.0,Thracian Valley,NaN,NaN,Jeff Jenssen,@worldwineguys,Castra Rubra 2010 CR Red (Thracian Valley),Bordeaux-style Red Blend,Castra Rubra
Canada,7878,Canada,"Smooth as silk and deeply concentrated, this o...",Riesling Icewine,94,60.0,Ontario,Niagara Peninsula,NaN,Paul Gregutt,@paulgwine,Cave Spring 2013 Riesling Icewine Riesling (Ni...,Riesling,Cave Spring
Chile,73993,Chile,"Clos Apalta, depending on your point of view, ...",Clos Apalta,95,90.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Lapostolle 2008 Clos Apalta Red (Colchagua Val...,Red Blend,Lapostolle
China,109989,China,This deep ruby-colored wine features a bouquet...,Noble Dragon,89,18.0,China,NaN,NaN,Mike DeSimone,@worldwineguys,Chateau Changyu-Castel 2009 Noble Dragon Red (...,Cabernet Blend,Chateau Changyu-Castel
Croatia,64094,Croatia,This 100% Teran from Istria has aromas of blue...,Terra Mare,91,33.0,Istria,NaN,NaN,Jeff Jenssen,@worldwineguys,Trapan 2013 Terra Mare Teran (Istria),Teran,Trapan
Cyprus,45270,Cyprus,This Cretan indigenous white offers aromas of ...,NaN,89,21.0,Lemesos,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsiakkas 2014 Xynisteri (Lemesos),Xynisteri,Tsiakkas
Czech Republic,7272,Czech Republic,"This red blend has a nose of fresh cherry, red...",Roucí,89,45.0,Moravia,NaN,NaN,Jeff Jenssen,@worldwineguys,Stapleton & Springer 2007 Roucí Red (Moravia),Red Blend,Stapleton & Springer
Egypt,110246,Egypt,"Ripe pear, apple and tropical fruit in the nos...",Caspar Blanc de Noirs,84,NaN,Egypt,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Sahara Vineyards 2008 Caspar Blanc de Noirs Gr...,Grenache,Sahara Vineyards
England,9909,England,"Touches of vanilla, cream and lovely hints of ...",Blanc de Blancs,95,70.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nyetimber 2010 Blanc de Blancs Chardonnay (Eng...,Chardonnay,Nyetimber
France,36528,France,This is a fabulous wine from the greatest Cham...,Brut,100,259.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Krug 2002 Brut (Champagne),Champagne Blend,Krug
Georgia,40429,Georgia,"From it's musky, perfumed to nose to it's inte...",Qvevri Traditional Kakhuri Dry Unfiltered Ambe...,92,25.0,Kakheti,NaN,NaN,Anna Lee C. Iijima,NaN,Alaverdi Monastery Cellar 2010 Qvevri Traditio...,Rkatsiteli,Alaverdi Monastery Cellar
Germany,16522,Germany,"With layers upon layers of spicy saffron, peac...",Kiedrich Gräfenberg Trockenbeerenauslese,98,775.0,Rheingau,NaN,NaN,Anna Lee C. Iijima,NaN,Robert Weil 2015 Kiedrich Gräfenberg Trockenbe...,Riesling,Robert Weil
Greece,9812,Greece,"Vanilla, citrus and white flowers on the nose ...",NaN,93,16.0,Mantinia,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Dionysos 2014 Moschofilero (Mantinia),Moschofilero,Dionysos
Hungary,45988,Hungary,"This ethereal Tokaji Aszú is golden in color, ...",6 Puttonyos Aszú Gold Label,97,80.0,Tokaji,NaN,NaN,Jeff Jenssen,@worldwineguys,Royal Tokaji 2013 6 Puttonyos Aszú Gold Label ...,White Blend,Royal Tokaji
India,6673,India,"The nose carries notes of cassis, blackberry a...",Dindori Reserve,93,20.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2011 Dindori Reserve Shiraz (Nashik),Shiraz,Sula
Israel,88685,Israel,"Inky red-violet to the eye, this wine has an i...",Reserve David Vineyard,94,25.0,Galilee,NaN,NaN,Mike DeSimone,@worldwineguys,Recanati 2011 Reserve David Vineyard Cabernet ...,Cabernet Sauvignon,Recanati
Italy,7335,Italy,Thick as molasses and dark as caramelized brow...,Occhio di Pernice,100,210.0,Tuscany,Vin Santo di Montepulciano,NaN,NaN,NaN,Avignonesi 1995 Occhio di Pernice (Vin Santo ...,Prugnolo Gentile,Avignonesi
Lebanon,4896,Lebanon,"Violet red to the eye, this wine is a blend of...",El,91,75.0,Lebanon,NaN,NaN,Mike DeSimone,@worldwineguys,Ixsir 2011 El Red (Lebanon),Red Blend,Ixsir
Luxembourg,78902,Luxembourg,"Made from Auxerrois, this delightful white has...",Bech-Kleinmacher Naumberg Grand Premier Cru,90,22.0,Moselle Luxembourgeoise,NaN,NaN,Jeff Jenssen,@worldwineguys,Domaines Vinsmoselle 2014 Bech-Kleinmacher Nau...,Auxerrois,Domaines Vinsmoselle
Macedonia,38503,Macedonia,This 100% Vranec presents the nose with black ...,Veritas,89,20.0,Tikves,NaN,NaN,Jeff Jenssen,@worldwineguys,Stobi 2011 Veritas Vranec (Tikves),Vranec,Stobi
Mexico,43799,Mexico,"A world-class wine regardless of origin, this ...",Amado IV,92,54.0,Valle de Guadalupe,NaN,NaN,Michael Schachner,@wineschach,Viñas de Garza 2007 Amado IV Red (Valle de Gua...,Red Blend,Viñas de Garza
Moldova,47131,Moldova,"Bright ruby in the glass, this wine is a blend...",Freedom Blend,91,25.0,Moldova,NaN,NaN,Jeff Jenssen,@worldwineguys,Purcari 2013 Freedom Blend Red (Moldova),Red Blend,Purcari
Morocco,39673,Morocco,"Aromas of black cherry, espresso bean and whit...",Médaillon,93,18.0,Zenata,NaN,NaN,Mike DeSimone,@worldwineguys,Ouled Thaleb 2012 Médaillon Red (Zenata),Red Blend,Ouled Thaleb
New Zealand,91851,New Zealand,"This full-bodied, richly tannic wine delivers....",Homage,95,100.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Trinity Hill 2013 Homage Syrah (Hawke's Bay),Syrah,Trinity Hill
Peru,63521,Peru,"Earthy, warm and ripe on the bouquet, with a b...",Sinfonía Tannat-Malbec-Petit Verdot,86,20.0,Ica,NaN,NaN,Michael Schachner,@wineschach,Tacama 2008 Sinfonía Tannat-Malbec-Petit Verdo...,Red Blend,Tacama
Portugal,42197,Portugal,This is the latest release of what has long be...,Barca-Velha,100,450.0,Douro,NaN,NaN,Roger Voss,@vossroger,Casa Ferreirinha 2008 Barca-Velha Red (Douro),Portuguese Red,Casa Ferreirinha
Romania,5761,Romania,This late harvest Sauvignon Blanc is honey gol...,Conocul Ambrozy,92,28.0,Recas,NaN,NaN,Jeff Jenssen,@worldwineguys,Cramele Recas 2013 Conocul Ambrozy Sauvignon B...,Sauvignon Blanc,Cramele Recas
Serbia,29284,Serbia,A blend of 60% Prokupac and 40% Cabernet Sauvi...,Sub Rosa,89,40.0,Župa,NaN,NaN,Jeff Jenssen,@worldwineguys,Budimir 2009 Sub Rosa Red (Župa),Red Blend,Budimir
Slovakia,22687,Slovakia,"Delicious scents of honey, apples and petrol l...",NaN,87,16.0,Muzla,NaN,NaN,Anna Lee C. Iijima,NaN,Château Bela 2008 Riesling (Muzla),Riesling,Château Bela
Slovenia,123819,Slovenia,"This has ebullient aromas of cherry blossom, g...",Veliko,92,50.0,Brda,NaN,NaN,Anna Lee C. Iijima,NaN,Movia 2007 Veliko White (Brda),White Blend,Movia
South Africa,9912,South Africa,Only 95 cases were made of this Bordeaux-style...,Book 17 XVII,95,330.0,Stellenbosch,NaN,NaN,Lauren Buzzeo,@laurbuzz,De Toren 2014 Book 17 XVII Red (Stellenbosch),Bordeaux-style Red Blend,De Toren
Spain,40307,Spain,Luscious prune and blackberry aromas come with...,Clon de la Familia,98,450.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Clon de la Familia (Ribera d...,Tinto Fino,Emilio Moro
Switzerland,14187,Switzerland,"A Swiss blend of Pinot Noir and Gamay, this de...",Dôle des Monts,90,30.0,Valais,NaN,NaN,Jeff Jenssen,@worldwineguys,Robert Gilliard 2012 Dôle des Monts Pinot Noir...,Pinot Noir-Gamay,Robert Gilliard
Turkey,29781,Turkey,"Aromas of black cherry, brambly berry, violet ...",Pendore,92,38.0,Aegean,NaN,NaN,Mike DeSimone,@worldwineguys,Kavaklidere 2010 Pendore Syrah (Aegean),Syrah,Kavaklidere
US,45798,US,Tasted in a flight of great and famous Napa wi...,NaN,100,200.0,California,Napa Valley,Napa,NaN,NaN,Cardinale 2006 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Cardinale
Ukraine,88511,Ukraine,"This has aromas of white flowers, especially h...",Reserve,88,9.0,Ukraine,NaN,NaN,Jeff Jenssen,@worldwineguys,Koblevo NV Reserve Riesling (Ukraine),Riesling,Koblevo
Uruguay,14119,Uruguay,Dried blackberry aromas include welcome notes ...,B6 Parcela Única,92,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2015 B6 Parcela Única Tannat (Canelones),Tannat,Bouza

In [ ]:
wine_df["country"].isna().value_counts()
# to check the NaN values

False    129908
True         63
Name: country, dtype: int64

In [ ]:
wine_df["price"].isna().value_counts()

False    120975
True       8996
Name: price, dtype: int64

In [ ]:
wine_df.groupby("country").price.agg([len,min,max,sum])

                          len   min     max        sum
country
Argentina                3800   4.0   230.0    92060.0
Armenia                     2  14.0    15.0       29.0
Australia                2329   5.0   850.0    81294.0
Austria                  3345   7.0  1100.0    86105.0
Bosnia and Herzegovina      2  12.0    13.0       25.0
Brazil                     52  10.0    60.0     1117.0
Bulgaria                  141   8.0   100.0     2065.0
Canada                    257  12.0   120.0     9071.0
Chile                    4472   5.0   400.0    91793.0
China                       1  18.0    18.0       18.0
Croatia                    73  12.0    65.0     1807.0
Cyprus                     11  11.0    21.0      179.0
Czech Republic             12  15.0    45.0      291.0
Egypt                       1   NaN     NaN        0.0
England                    74  25.0    95.0     3566.0
France                  22093   5.0  3300.0   731289.0
Georgia                    86   9.0    40.0     1623.0
Germany                  2165   5.0   775.0    89586.0
Greece                    466   8.0    79.0    10310.0
Hungary                   146  10.0   764.0     5894.0
India                       9  10.0    20.0      120.0
Israel                    505   8.0   150.0    15535.0
Italy                   19540   5.0   900.0   670873.0
Lebanon                    35  13.0    75.0     1074.0
Luxembourg                  6  16.0    30.0      140.0
Macedonia                  12  15.0    20.0      187.0
Mexico                     70   8.0   108.0     1875.0
Moldova                    59   8.0    42.0      988.0
Morocco                    28  14.0    40.0      546.0
New Zealand              1419   7.0   130.0    37112.0
Peru                       16  10.0    68.0      289.0
Portugal                 5691   5.0  1000.0   127814.0
Romania                   120   4.0   320.0     1829.0
Serbia                     12  15.0    42.0      294.0
Slovakia                    1  16.0    16.0       16.0
Slovenia                   87   7.0    90.0     1985.0
South Africa             1401   5.0   330.0    31897.0
Spain                    6645   4.0   770.0   185459.0
Switzerland                 7  21.0   160.0      597.0
Turkey                     90  14.0   120.0     2217.0
US                      54504   4.0  2013.0  1984659.0
Ukraine                    14   6.0    13.0      129.0
Uruguay                   109  10.0   130.0     2878.0

In [ ]:
wine_df.groupby("country").points.agg([len,min,max,sum])

                          len  min  max      sum
country
Argentina                3800   80   97   329499
Armenia                     2   87   88      175
Australia                2329   80  100   206304
Austria                  3345   82   98   301389
Bosnia and Herzegovina      2   85   88      173
Brazil                     52   80   89     4403
Bulgaria                  141   80   91    12399
Canada                    257   82   94    22968
Chile                    4472   80   95   386799
China                       1   89   89       89
Croatia                    73   81   91     6367
Cyprus                     11   85   89      959
Czech Republic             12   84   89     1047
Egypt                       1   84   84       84
England                    74   89   95     6777
France                  22093   80  100  1962855
Georgia                    86   82   92     7541
Germany                  2165   81   98   194529
Greece                    466   82   93    40674
Hungary                   146   81   97    13022
India                       9   87   93      812
Israel                    505   80   94    44678
Italy                   19540   80  100  1730506
Lebanon                    35   82   91     3069
Luxembourg                  6   88   90      532
Macedonia                  12   84   89     1042
Mexico                     70   80   92     5968
Moldova                    59   82   91     5145
Morocco                    28   85   93     2480
New Zealand              1419   80   95   125302
Peru                       16   80   86     1337
Portugal                 5691   80  100   502232
Romania                   120   82   92    10368
Serbia                     12   86   89     1050
Slovakia                    1   87   87       87
Slovenia                   87   82   92     7662
South Africa             1401   82   95   123367
Spain                    6645   80   98   580031
Switzerland                 7   83   90      620
Turkey                     90   84   92     7928
US                      54504   80  100  4827077
Ukraine                    14   82   88     1177
Uruguay                   109   80   92     9456

Multiple Indexing

In [ ]:
country_reviewed= wine_df.groupby(["country","province"]).description.agg(len)
country_reviewed

country    province
Argentina  Mendoza Province    3264
           Other                536
Armenia    Armenia                2
Australia  Australia Other      245
           New South Wales       85
                               ...
Uruguay    Juanico               12
           Montevideo            11
           Progreso              11
           San Jose               3
           Uruguay               24
Name: description, Length: 425, dtype: int64

In [ ]:
mi= country_reviewed.index
mi

MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)

In [ ]:
country_reviewed.reset_index()

       country          province  description
0    Argentina  Mendoza Province         3264
1    Argentina             Other          536
2      Armenia           Armenia            2
3    Australia   Australia Other          245
4    Australia   New South Wales           85
..         ...               ...          ...
420    Uruguay           Juanico           12
421    Uruguay        Montevideo           11
422    Uruguay          Progreso           11
423    Uruguay          San Jose            3
424    Uruguay           Uruguay           24

[425 rows x 3 columns]

In [ ]:
country_reviewed.sort_values()

country       province
Greece        Muscat of Kefallonian        1
              Sterea Ellada                1
              Thraki                       1
South Africa  Paardeberg                   1
Brazil        Serra do Sudeste             1
                                       ...
US            Oregon                    5373
Italy         Tuscany                   5897
France        Bordeaux                  5941
US            Washington                8639
              California               36247
Name: description, Length: 425, dtype: int64

In [ ]:
country_reviewed.sort_values(ascending=False)

country       province
US            California         36247
              Washington          8639
France        Bordeaux            5941
Italy         Tuscany             5897
US            Oregon              5373
                                 ...
Croatia       Krk                    1
New Zealand   Gladstone              1
South Africa  Piekenierskloof        1
Chile         Coelemu                1
Greece        Beotia                 1
Name: description, Length: 425, dtype: int64

In [ ]:
country_reviewed.sort_values()

country       province
Greece        Muscat of Kefallonian        1
              Sterea Ellada                1
              Thraki                       1
South Africa  Paardeberg                   1
Brazil        Serra do Sudeste             1
                                       ...
US            Oregon                    5373
Italy         Tuscany                   5897
France        Bordeaux                  5941
US            Washington                8639
              California               36247
Name: description, Length: 425, dtype: int64

In [ ]:
wine_df.groupby("price").points.max()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [ ]:
price= wine_df.groupby("variety").price.agg([min,max])

In [ ]:
sorted_varieties = price.sort_values(by=["min","max"], ascending=True)
sorted_varieties

                                min    max
variety
Pinot Grigio                    4.0   70.0
Malbec-Syrah                    4.0   78.0
White Blend                     4.0  375.0
Tempranillo                     4.0  600.0
Cabernet Sauvignon              4.0  625.0
...                             ...    ...
Roscetto                        NaN    NaN
Sauvignon Blanc-Sauvignon Gris  NaN    NaN
Tempranillo-Malbec              NaN    NaN
Vital                           NaN    NaN
Zelen                           NaN    NaN

[707 rows x 2 columns]

In [ ]:
wine_df.groupby("taster_name").points.mean()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [ ]:
mi= wine_df.groupby(["country","variety"]).variety.agg(len)
mi

country    variety
Argentina  Barbera                         1
           Bonarda                       105
           Bordeaux-style Red Blend       89
           Bordeaux-style White Blend      1
           Cabernet Blend                  8
                                        ...
Uruguay    Tannat-Cabernet Franc           2
           Tannat-Merlot                   6
           Tannat-Syrah                    1
           Tempranillo-Tannat              1
           White Blend                     1
Name: variety, Length: 1612, dtype: int64

In [ ]:
mi2=mi.index
mi2

MultiIndex([('Argentina',                           'Barbera'),
            ('Argentina',                           'Bonarda'),
            ('Argentina',          'Bordeaux-style Red Blend'),
            ('Argentina',        'Bordeaux-style White Blend'),
            ('Argentina',                    'Cabernet Blend'),
            ('Argentina',                    'Cabernet Franc'),
            ('Argentina', 'Cabernet Franc-Cabernet Sauvignon'),
            ('Argentina',             'Cabernet Franc-Malbec'),
            ('Argentina',                'Cabernet Sauvignon'),
            ('Argentina', 'Cabernet Sauvignon-Cabernet Franc'),
            ...
            (  'Uruguay',                        'Pinot Noir'),
            (  'Uruguay',                         'Red Blend'),
            (  'Uruguay',                              'Rosé'),
            (  'Uruguay',                   'Sauvignon Blanc'),
            (  'Uruguay',                            'Tannat'),
            (  'Uruguay',             'Tannat-Cabernet Franc'),
            (  'Uruguay',                     'Tannat-Merlot'),
            (  'Uruguay',                      'Tannat-Syrah'),
            (  'Uruguay',                'Tempranillo-Tannat'),
            (  'Uruguay',                       'White Blend')],
           names=['country', 'variety'], length=1612)

# **Data Types and Missing Values**

In [ ]:
wine_df.price.dtype

dtype('float64')

In [ ]:
wine_df.dtypes

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [ ]:
wine_df.points.astype("float") #to change dtype from "int" to "float"

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [ ]:
wine_df[pd.isnull(wine_df.country)]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy
129407,129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [ ]:
wine_df["country"].isna().value_counts()

False    129908
True         63
Name: country, dtype: int64

In [ ]:
#to fill NaN values
wine_df.region_2.fillna("unknown")

0                   unknown
1                   unknown
2         Willamette Valley
3                   unknown
4         Willamette Valley
                ...
129966              unknown
129967         Oregon Other
129968              unknown
129969              unknown
129970              unknown
Name: region_2, Length: 129971, dtype: object

In [ ]:
wine_df.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

In [ ]:
wine_df[pd.isnull(wine_df.price)]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
30,30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone
31,31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,129844,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Caparzo 2006 Doga delle Clavule (Morellino di...,Sangiovese,Caparzo
129860,129860,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portuguese Red,Quinta da Pacheca
129863,129863,Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Seacampo 2011 Reserva Red (Dão),Portuguese Red,Seacampo
129893,129893,Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Le Mandolare 2015 Corte Menini (Soave Classico),Garganega,Le Mandolare
129964,129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart

In [ ]:
fillwithunknown= wine_df.region_1.fillna("unknown")
reviews_per_region = fillwithunknown.value_counts().sort_values(ascending= False)
reviews_per_region

unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perrières            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: region_1, Length: 1230, dtype: int64

# **Renaming and Combining**

In [ ]:
wine_df.rename(columns={"points":"score"})

,Unnamed: 0,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit